baseURL = "https://mkonefal.pl"
title = "MKonefal"
theme = "etch"
languageCode = "pl-PL"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Personal site"
  copyright = "Copyright © 2024 Mateusz Konefał"
  dark = "on"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier = "links"
    name = "links"
    title = "links"
    url = "/links/"
    weight = 30


[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
